### ISSUE TITLE
A simple question with matplotlib plot window

### ISSUE THREAD

**Issue by wshchzhq** [aroberge/easygui_qt#22] opened 2015-03-02 22:32 UTC
Hey, all,
I have a question with matplotlib. When I run a simple code like this:

import matplotlib.pyplot as plt
import easygui_qt as easy
plt.ion()
plt.plot([1,2,3])
easy.get_int()

after I enter the integer and close the qt window, the plot window just crashes and cannot be closed. Any ideas?

This won't happen when I use easygui. So tkinter does not have such issue.

**Comment by aroberge** [comment] 2015-03-02 23:43
Easygui_qt starts a QtApplication for each individual widget and closes it.  My understanding of the Qt framework is that it allows only one QtApplication running at a time; closing it might very well be the cause of the plot window crash.

**Comment by wshchzhq** [comment] 2015-03-03 16:00
Thanks, so any ideas to solve this? Or I may turn to easygui probably.

**Comment by aroberge** [comment] 2015-03-03 17:14
If easygui works for you, then I'd suggest to use it instead.

**Comment by triccare** [comment] 2015-03-04 15:38
Which python interpreter are you using? If ipython, look up forcing the use of pyqt with matplotlib in ipython. there may simply be a conflict of gui backends.

**Comment by wshchzhq** [comment] 2015-03-04 22:42
I use spyder. I tried Ipython console in spyder and only if I use qt as gui backends, the window would crash. So I guess I just use inline or wx. Thanks a lot!

**Closed** 2016-11-28 21:54 UTC
